import Providers from '@/providers/providers';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html suppressHydrationWarning className='font-pretendard'>
      <head>
        <link rel='preconnect' href='https://cdn.jsdelivr.net' />
        <link rel='dns-prefetch' href='https://cdn.jsdelivr.net' />
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/pretendard@latest/dist/web/variable/pretendardvariable.css'
        />
      </head>
      <body className='antialiased'>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
